sudo: required
dist: trusty

language: node_js

node_js:
  - '10'

cache:
  directories:
    - /node_modules

after_script:
  - npm run coverage
  - npm test
  - npm run cov:send
  - npm run cov:check
